import type { Metadata } from "next";
import "./globals.css";
// import Sidebar from "./components/organisms/ Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-black">
      <body>
        <div>
          {/* <Sidebar /> */}
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
